from snakemake.utils import min_version

min_version("9.0.0")

configfile: "config/config.yaml"

include: "rules/create.smk"

TARGETS = [
    f"{config['data_directory']}/A.tsv",
    f"{config['data_directory']}/B.tsv"
]

rule all:
    input:
        TARGETS
