from snakemake.utils import min_version

min_version("9.0.0")

configfile: "config/config.yaml"

include: "rules/create.smk"

rule all:
    input:
        expand("{data_directory}/A.tsv", data_directory=config["data_directory"]),
        expand("{data_directory}/B.tsv", data_directory=config["data_directory"])
